---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
    name: catalog-web-cache

spec:
    refreshInterval: 12h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: web-cache
        creationPolicy: Owner
    dataFrom:
        # Reuses the same shared Redis instance's client credentials as catalog-api, since this
        # app's cache is just an optimization over the same catalog-api data, not separate state.
        - extract:
              key: /sweetrpg/catalog/cache/auth
