---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
    name: catalog-web-misc

spec:
    refreshInterval: 12h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: web-misc
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: /sweetrpg/catalog/web/misc
        - sourceRef:
            generatorRef:
                apiVersion: generators.external-secrets.io/v1alpha1
                kind: Password
                name: "catalog-web-health-token"
          rewrite:
            - regexp:
                source: "(.*)"
                target: HEALTH_TOKEN
