apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-catalog

resources:
  - ../../base
  - configmaps.yaml
  - secrets.yaml
  - ingress.yaml
  - middlewares.yaml
  - pod-monitor.yaml

labels:
  - pairs:
      app.kubernetes.io/name: catalog-web
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: catalog
      com.sweetrpg/env: local
    includeSelectors: false
    includeTemplates: true

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: catalog-web
    newName: ghcr.io/sweetrpg/catalog-web
    newTag: v0.0.1
