name: PR Validation

on:
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: write

jobs:
  validate:
    uses: sweetrpg/github-actions/.github/workflows/swift-ci.yaml@3-add-code-coverage
    with:
      publish-coverage: false
    secrets: inherit
